### ISSUE TITLE
Not detecting state of game properly

### ISSUE THREAD

**Issue by Frritz** [little-fort/booster-bot#2]
Hey, I just started using this and I have noticed it skipping turns basically every game.
Most frequently it does not wait long enough for a turn to resolve and starts trying to play cards before it can, so it cycles through them all and then continually tries to end the turn having played nothing even though there are many playable cards in hand.
Or sometimes it will start trying to collect boosters thinking the match is over even though it isn't so it just keeps ending the turn.
Happy to provide any screenshots/logs/info that may help.

**Comment by little-fort** [comment]
Hi! Yes that is expected behavior for a couple reasons. Because of how the "End Turn" button text is a bit smaller than the "Retreat" button, while also fading in/out depending on turn state, the OCR is consistently unable to determine what it says. So rather than attempting to read turn state, the bot follows a regular timed cadence of attempting to play cards and then progressing the turn. So there will often be times when it progresses without playing anything even when it could have. OCR failures are also why the bot will start checking if the game is over even though it's clearly not. Even if this happens, the bot will eventually get back on track and keep doing its thing if left alone.

There are only two possible fixes for this: use a better OCR package or give the bot more time to process before performing actions. OCR libraries that are consistently good have licenses costing well over $1,000 at minimum, whereas the one I'm using is free, so... 🤷🏾‍♂️ I have played around with giving the bot more time to process between actions, but then it will drag on turns for too long and matches take forever. Not only does that result in a lower booster/XP farming rate, but it's also creating a bad experience for the opponents.

It's also important to remember that for the sake of farming boosters, playing cards is irrelevant anyway. Booster rewards are only based on turns completed—the bot plays cards just to make it less detectable while also completing some missions. If you only care about maximizing XP, then using an Agatha deck will ensure cards get played before the turn is progressed.

**Comment by Frritz** [comment]
Makes sense.
I just wasn't sure if there was some issue on my end or if that is expected behavior.
I was more so using it for XP and found that it works great with Agatha as long as something doesn't allow her to come down early in which case it just skips playing anything every turn afterward pretty consistently.

I realize that may not be feasible depending on how the application was written, but maybe the turn counter on the end turn button could be utilized to determine when is has successfully gone from 1 turn to the next?
Then it could have some reference for when to wait for card/location animations to resolve before cards are playable instead of using a set amount of time after pressing end turn.
That is assuming the OCR is able to pick up on that consistently enough.
Just a thought from someone who knows very little about coding, lol.
Either way thanks for your work on this and looking forward to seeing any future improvements.

**Comment by little-fort** [comment]
Well you motivated me to rework some of the core app logic lol, and I have published a new [release preview](https://github.com/little-fort/booster-bot/releases/tag/v1.2.0-preview) that I could use some feedback on. The big changes include support for farming Conquest mode (Proving Grounds only for now) and significantly improved consistency with the app's ability to detect game state and play cards. Regarding that last point, I moved away from the use of a third-party OCR library and wrote my own detection method from scratch.

For now, all the good changes were only applied to the new Conquest farming mode—the Ranked farming mode logic is unchanged. But if all goes well, I should have the Ranked logic reworked in the next couple days, and then I'll publish an official release.

In the meantime, it would be helpful if you could try out the preview build and let me know what you think!

**Comment by Frritz** [comment]
Oh, awesome.
I'll give it a try when I get a chance and let you know how it goes.

**Comment by Frritz** [comment]
I haven't had a chance to test conquest mode yet, but attempting to start on ranked mode returns the following:

****************************************************
          BoosterBot v1.2.0-preview.2
****************************************************

Checking if game is on main menu...
Parameter is not valid.

   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
   at System.Drawing.Bitmap..ctor(String filename)
   at BoosterBot.BoosterBot.ReadArea(Int32 x, Int32 y, Int32 width, Int32 height, Boolean export, String image) in D:\a\booster-bot\booster-bot\src\BoosterBot\BoosterBot.cs:line 444
   at BoosterBot.BoosterBot.ReadArea(Rect crop, String image, Int32 sampleCount, Boolean export) in D:\a\booster-bot\booster-bot\src\BoosterBot\BoosterBot.cs:line 431
   at BoosterBot.BoosterBot.IsOnMainMenu() in D:\a\booster-bot\booster-bot\src\BoosterBot\BoosterBot.cs:line 158
   at BoosterBot.BoosterBot.Run() in D:\a\booster-bot\booster-bot\src\BoosterBot\BoosterBot.cs:line 53
   at BoosterBot.Program.Main(String[] args) in D:\a\booster-bot\booster-bot\src\BoosterBot\Program.cs:line 74

Press [Enter] to continue...

**Comment by little-fort** [comment]
Yeah like I mentioned, the ranked logic was sort of "under construction" in that build and I was mostly just testing Conquest logic. But it's all good, I was able to get the revamped logic ported over to ranked and felt comfortable publishing a new release:

https://github.com/little-fort/booster-bot/releases/tag/v1.2.0

This one has the Conquest functionality in place and should also see much more consistent and effective performance in Ranked as well

**Comment by little-fort** [comment]
I'm definitely good with the anti-detection measures in place for now. There's enough present that SD would have to commit a non-trivial amount of time to it, and they haven't been particularly militant about these kinds of bots/scripting techniques so far. If they were to come out with a stronger stance (or if this somehow blew up in popularity and started getting their attention), there's definitely room to add more variability, but it seems like overkill for now. There are people who run far more simplistic bots/auto-clickers daily and most do just fine unless they really go overboard with it.

For what it's worth, I first wrote this bot back in January and I've been using it every season since then for post-Infinite farming. I've racked up 40,000+ boosters with Agatha in that time frame and never caught any bans from it, so I'm content to let it ride for now.

But of course, as I say on the main page, this is all purely hypothetical and for education purposes only 😉

**Comment by Frritz** [comment]
K cool.
I've run into a few issues now that I've had some more time to test.

Trying to launch conquest mode does not work for me.
It gets to the game mode tab but cannot make it into the conquest menu itself.

Ranked mode works great while it is running, but the app has crashed on me twice so far after running for a few games.
I couldn't find a log file to see if it had any info on why it is crashing, and I haven't been able to catch it in the console window before it crashes.

**Comment by Frritz** [comment]
Discovered the app is crashing because it's being detected as ransomware.

**Comment by little-fort** [comment]
Well that's fascinating... I've tested it on a couple different machines and haven't had that issue. Looks like it's getting blocked from simply accessing the screencapped game image from the disk. Are you on Windows 10 or 11? And do you have any third-party antivirus software installed (anything other than Windows Defender)? 

Also I put up a [new build](https://github.com/little-fort/booster-bot/releases/tag/v1.2.2) that will output log files if you want to use that for easier log sharing. Logs will all go to the `logs\` folder in the application directory

**Comment by Frritz** [comment]
I'm on Windows 10.
Malwarebytes is what killed it.
The error that the app gives before it dies may just be it recognizing that it's getting quarantined rather than an issue with the app itself functioning.
I ran v1.1 for an extended period of time multiple times without any issue so not sure exactly what aspect could be causing it to get blocked now.

**Comment by little-fort** [comment]
Okay, that makes sense. It comes down to the differences in how the app detects UI components. The v1.1 logic was using OCR to take crops of the game screen and attempt parsing out text, whereas the current logic makes multiple crops, does a little bit of image manipulation to strip out things like gradients, filters, or text effects, and then it compares the result to an expected reference image (found in the `reference\` directory). The latter method, as you've seen, is much more consistent, but does involve more writing & reading to/from the disk (plus more frequent screencaps), and apparently Malwarebytes doesn't like that.

If you whitelist the app directory directory in MWB, that should clear up the issue though

**Comment by Frritz** [comment]
Ah, OK.

Conquest still does not work for me unfortunately.
It seems like it doesn't attempt to click on the conquest button for some reason, then continues through checking if it's on proving grounds before looping back to the start.

**Comment by little-fort** [comment]
Which screen is it failing at specifically? Is it stuck at the main screen, or does it navigate to the Game Modes tab and then fail to click on the Conquest banner?

**Comment by Frritz** [comment]
It gets to the game modes tab and then fails to click.

[2023-08-01 22:29:46] Navigating to Game Modes tab...
[2023-08-01 22:29:51] Navigating to Conquest menu...
[2023-08-01 22:29:51] Starting match loop...
[2023-08-01 22:29:52] Making sure lobby type is set to Proving Grounds...`

**Comment by little-fort** [comment]
Try this one, tried to give it more leeway when entering the Conquest menu:

https://github.com/little-fort/booster-bot/releases/tag/v1.2.3

**Comment by Frritz** [comment]
Still stalling out in the same spot.
I'm not sure if it's trying to click and missing the button for some reason or what.
My monitor is set to 1080 even though that isn't the native resolution, but scaling is 100% so I left it alone like the instructions say.
All other functions appear to work as intended though so if something is off with that then it can't be by much.

I went to adjust the scaling while launching just in case but I get an error.
BoosterBot.exe --scaling 1.25
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at BoosterBot.Program.Main(String[] args) in D:\a\booster-bot\booster-bot\src\BoosterBot\Program.cs:line 10

**Comment by little-fort** [comment]
That's really interesting. What is the native resolution of the monitor? And when it gets to the game modes screen, do you see the cursor hovering over the Conquest button and it just seems like it isn't clicking? Or is the cursor somewhere else on the screen and missing the button entirely?

**Comment by Frritz** [comment]
1920x1200.
At the step where it says navigating to conquest menu the cursor appears to snap to the top of the screen.

**Comment by little-fort** [comment]
Give this one a try: https://github.com/little-fort/booster-bot/releases/tag/v1.2.5

Also just to confirm, you can leave the `scaling` parameter out if your system display scaling is set to 100%. That shouldn't be causing the issue for you

**Comment by Frritz** [comment]
K I figured but was just thinking of any possible cause.

Newest release does get into the conquest menu but then when it's trying to swipe over to proving grounds the cursor is a little too high so it never actually moves.
If I manually swipe it over to proving grounds it recognizes it and starts normally.

**Comment by little-fort** [comment]
One more time lol...

https://github.com/little-fort/booster-bot/releases/tag/v1.2.6

**Comment by Frritz** [comment]
This one is actually higher lol.
It's trying to swipe at the very top of the screen now.

**Comment by little-fort** [comment]
Oof. This honestly has been a fascinating look into how arbitrary the values for display coordinates are in Windows...

Anyway, here we go again: https://github.com/little-fort/booster-bot/releases/tag/v1.3.0-preview

This one is a little different because I'm adding the optional ability to farm higher tiers of Conquest with tickets. Mostly because I now have a fat stack of Silver tickets and there's no way I'm about to manually play them all out lol. You'll see new menu options on startup but you can just select Proving Grounds to keep the behavior the same

**Comment by Frritz** [comment]
Everything seems to be functioning like it should with this release, thanks.
I didn't test the gold conquest option yet, but other conquest tiers work and ranked works as well.
Only thing is it prompts for a conquest tier when selecting ranked but it works fine once you pick any tier.
Hopefully the upcoming UI changes won't impact functionality.

**Comment by little-fort** [comment]
Awesome, here's the official 1.3 build with that ranked menu thing fixed: https://github.com/little-fort/booster-bot/releases/tag/v1.3.0

> Hopefully the upcoming UI changes won't impact functionality.

I can safely assume it's going to break the whole thing tbh—I wouldn't expect the bot to work at all after that update drops. Even if they do the bare minimum and just widen the UI to fit the whole screen, that would still mean I'd have to update all of the UI reference points before the bot would work again.

But the way they're talking about it, it seems like the PC client will have a distinct look and feel from the mobile version, which would probably require deeper changes to the navigation and detection logic. On the positive side, if they are truly building a PC-focused UI that works with keyboard inputs, it could actually simplify things a lot for me if it means I can swap out much of the image detection and mouse simulation logic for straightforward keystroke patterns

In any case, you've been an excellent QA tester for me, thanks for all your help!

**Comment by Frritz** [comment]
Happy to help.
The application has improved a lot in the past week so well done.
I'll let you know if I run into anything on future releases.
